language: node_js
node_js:
- '7.4'
addons:
  apt:
    packages:
    - oracle-java8-set-default
  sauce_connect: true
before_install:
- export TZ=Europe/Madrid
script:
- npm run test
env:
  global:
  - secure: ki4GZ/fXntoxLrMviA9NXhQnjO7EIyxyF3HweeHicDj1a+PjUMlEOpXQ95DTy+ZkApme/iEexUWP+GSpKq3LkvF5JgNNsGlyteekQtY/1zkACFGSC1uKSpp0l6qwpHneAvET/nOp+A15P1V5F26A+mr1rOoabxhqIE6vBMd2wRCqOKknDkHJyaz1/1b71HULb6mFfvHckFvRFD+mhQhnVrrRqNcylm9WFG8Yh1P9LrAwdISLTzNwaXTpULEm/CstuzYG7+nUbrMTXpF5x21bd0sHBiae4P/LYanxi0QgVJ9+QG8Pb5MPfYqxlY0ixs22wCQnQDVwOrLhBqNJ0mSwjNjFDaRneSzrvG/+rY1B3Z0eRq79sRIvmPlQzXovKzBWwIIxGB0VFbP2KJlw1P/eqS9920GPcmKYn7ZWc0N2zzXQ8XmZvAmAow/OoPVfnBTX0UZRDHfN8EyGGgST4E98KHa5qY+W8e7PzoNESCTWNv472jaifqD1+Da11AVCbgOapLpxi7raHJJPwEJa4nW0JvZA/wnUnOOaP5xcPN/Fjtmeg6SgFYXmJUxvO1673rUcS9ePhUjiQXxTBNWu+oj8XAgjNIrtH/bJYKyKJKpjGcXMRAkDi3QqkF5FCyhso78sxxtUFzdetDx6EH/Hhi1yrjG/Y2rsmfYQdWrATMQfVjw=
  - secure: YOTK+9OzKmhIcx4f3vwthRGLd1/rUB+Y7nWzXR607hLq3H7XMDsnewYcQJkD/AbSsA6skjDgkAJ0RjmbAgsHU2Vjm84Qr4DRdxlEOngWgB52sFkZhqZa1xwQ0i4WGJYgYMyu1uDWMT89WfxlMpU+XcnhJUbykmTQAWzTcBtcpOcw/WrcPufQs3rhRLD6Dv0/rRObDchU+YpDjvtmPt8XtbWloV10ZPwsSTuvAAudagPmaW3wpRHN6eKiy5gZCXXzoxGRZptvZ8evxUxcQB8LAAIjmIRwg4kqpT+cuQACoHCzR8mmrEsw5MWTI37zJlJyo7llQdPb0m+1m/4tiPeSdzn0b8PGXSCCwz0nEZDOqwt/exsdXjS58wFtyy9DV3djUlVmu5g92bUF4V0buS+cKzBak6ol2cOBNi79pz1+c/DW6W0SisRJNeuqVxJ1sMLFiJSq7IFZU9Kd+E/7pWFe7ZPdsGhi9Ikvs0Ni8XPXnZzosSbmiT3U88BPRUzSOhrd3eSunnuKHTehhwTsdQSHWNWvImPC4WiO8MNFtEaoYUag9lthUz55LddthQXSVas38gk4F35xdzK0+zwYSR+ZLRbCmJmEwMW2ag0bmRJsW3ejzORwVjCHfwCvaausWZtTxiwvEkkHyXXjELs2xyrSKk8R8WCkcDB5kOwHlwRqL2Y=
